#pragma kernel CSMain
RWStructuredBuffer<float> terrain;
float2 Random(float2 vec);
float Perlin(float2 pos);
float mix(float x, float y, float w) { return x * (1 - w) + y * w; }

[numthreads(1,1,1)]

void CSMain (uint3 id : SV_DispatchThreadID)
{
	terrain[id.y * 4 + id.x] = Perlin(id.xy);
}
float2 Random(float2 vec)
{
	vec = float2(dot(vec, float2(127.1, 311.7)), dot(vec, float2(269.5, 183.3)));
	return -1.0 + 2.0 * frac(sin(vec)*43758.5453123);
}
float Perlin(float2 pos)
{
	pos /= 2.0f;
	float2 pi = floor(pos);
	float2 pf = frac(pos);
	float2 w = pf * pf * (3.0 - 2.0 * pf);
	
	return 100*mix(mix(dot(Random(pi + float2(0.0, 0.0)), pf - float2(0.0, 0.0)),
		dot(Random(pi + float2(1.0, 0.0)), pf - float2(1.0, 0.0)), w.x),
		mix(dot(Random(pi + float2(0.0, 1.0)), pf - float2(0.0, 1.0)),
			dot(Random(pi + float2(1.0, 1.0)), pf - float2(1.0, 1.0)), w.x),
		w.y);
	
}
